### ISSUE TITLE
docker-sync-stack start fails

### ISSUE THREAD

**Issue by sandrodz** [EugenMayer/docker-sync#142]
on OSX `docker-sync-stack start`

```
/Users/sandro/.gem/ruby/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:105:in `private': nil is not a symbol (TypeError)
	from /Users/sandro/.gem/ruby/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:105:in `<class:Mapper>'
	from /Users/sandro/.gem/ruby/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:5:in `<module:Compose>'
	from /Users/sandro/.gem/ruby/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:2:in `<top (required)>'
	from /Users/sandro/.gem/ruby/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose.rb:10:in `require_relative'
	from /Users/sandro/.gem/ruby/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose.rb:10:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/sandro/.gem/ruby/2.0.0/gems/docker-sync-0.1.2/tasks/stack/stack.thor:6:in `<top (required)>'
	from /Users/sandro/.gem/ruby/2.0.0/gems/docker-sync-0.1.2/bin/docker-sync-stack:23:in `load'
	from /Users/sandro/.gem/ruby/2.0.0/gems/docker-sync-0.1.2/bin/docker-sync-stack:23:in `block in <top (required)>'
	from /Users/sandro/.gem/ruby/2.0.0/gems/docker-sync-0.1.2/bin/docker-sync-stack:21:in `each'
	from /Users/sandro/.gem/ruby/2.0.0/gems/docker-sync-0.1.2/bin/docker-sync-stack:21:in `<top (required)>'
	from /Users/sandro/.gem/ruby/2.0.0/bin/docker-sync-stack:23:in `load'
	from /Users/sandro/.gem/ruby/2.0.0/bin/docker-sync-stack:23:in `<main>'
```

**Comment by EugenMayer** [comment]
Seems like you finde it already, right? There Showdown be some mix up with you Ruby version and 1.9 is used, fix your rbenv?

**Comment by sandrodz** [comment]
hm, I don't use rbenv, I use system ruby from OSX 2.0.0

```
ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
```

**Comment by EugenMayer** [comment]
could you please open a issue on https://github.com/xeger/docker-compose to follow up on this one, this is an issue for docker-compose parsing.

Do you have sierra already? Since AFAIR El Capitan has still ruby 1.9

**Comment by sandrodz** [comment]
I've Sierra yes. Ruby version is 2.0.0 but El capitan was the same.

I opened issue: https://github.com/xeger/docker-compose/issues/40

**Comment by EugenMayer** [comment]
fixed with the new dependency on docker-compose 1.0
