### ISSUE TITLE
Make dest in sync-configuration optional

### ISSUE THREAD

**Issue by matleh** [EugenMayer/docker-sync#256]
Version 0.2 uses volumes (way to go!) which are much more flexible than the old data-containers.
As I understand it, the `dest` configuration parameter is no longer needed, since the mount-point is now given when the volume is used. The sync-container is just there to copy the data between host and volume - it can mount the volume at any location, without consequences for the container that uses the volume.

However, specifying a sync without `dest` throws an error during `docker-sync start`.

```
/usr/local/Cellar/gem-docker-sync/0.2.0/gems/docker-sync-0.2.0/lib/docker-sync/sync_manager.rb:95:in `block in validate_sync_config': fuse_src does not have dest configuration value set - this is mandatory (RuntimeError)
	from /usr/local/Cellar/gem-docker-sync/0.2.0/gems/docker-sync-0.2.0/lib/docker-sync/sync_manager.rb:94:in `each'
	from /usr/local/Cellar/gem-docker-sync/0.2.0/gems/docker-sync-0.2.0/lib/docker-sync/sync_manager.rb:94:in `validate_sync_config'
	from /usr/local/Cellar/gem-docker-sync/0.2.0/gems/docker-sync-0.2.0/lib/docker-sync/sync_manager.rb:85:in `block in validate_config'
	from /usr/local/Cellar/gem-docker-sync/0.2.0/gems/docker-sync-0.2.0/lib/docker-sync/sync_manager.rb:84:in `each'
	from /usr/local/Cellar/gem-docker-sync/0.2.0/gems/docker-sync-0.2.0/lib/docker-sync/sync_manager.rb:84:in `validate_config'
	from /usr/local/Cellar/gem-docker-sync/0.2.0/gems/docker-sync-0.2.0/lib/docker-sync/sync_manager.rb:35:in `load_configuration'
	from /usr/local/Cellar/gem-docker-sync/0.2.0/gems/docker-sync-0.2.0/lib/docker-sync/sync_manager.rb:25:in `initialize'
	from /usr/local/Cellar/gem-docker-sync/0.2.0/gems/docker-sync-0.2.0/tasks/sync/sync.thor:30:in `new'
	from /usr/local/Cellar/gem-docker-sync/0.2.0/gems/docker-sync-0.2.0/tasks/sync/sync.thor:30:in `start'
	from /usr/local/Cellar/gem-docker-sync/0.2.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/gem-docker-sync/0.2.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/gem-docker-sync/0.2.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/Cellar/gem-docker-sync/0.2.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/Cellar/gem-docker-sync/0.2.0/gems/docker-sync-0.2.0/bin/docker-sync:14:in `<top (required)>'
	from /usr/local/bin/docker-sync:5:in `load'
	from /usr/local/bin/docker-sync:5:in `<main>'
```

**Comment by EugenMayer** [comment]
This is actually a pretty damn good point :) 

I think there are other reasons we need this for, e.g. for fsevents and other things, but i am not sure and i have to verify that. other then that, as you say, the parameter does not make any sense anmore

**Comment by EugenMayer** [comment]
@matleh any way i can motivate you contributing in this area here? You pointed out all the key points, so why you just not grab the credits for those? :)

**Comment by matleh** [comment]
@EugenMayer I can take a look - no promises how much time I actually find for this, though.

**Comment by EugenMayer** [comment]
thank you @matleh for contributing and fixing this one!
