### ISSUE TITLE
RVM issue when upgrading

### ISSUE THREAD

**Issue by wulftone** [EugenMayer/docker-sync#319]
I tried to have it automatically upgrade and ran into this issue:

```bash
$ bundle exec docker-sync-stack start
     warning  The installation progress of docker-sync 0.3.0 has changed, brew is now mandatory - you need to uninstall unox ! :

_Please_ read :): https://github.com/EugenMayer/docker-sync/wiki/1.3-Upgrade-Guide

          ok  sudo rm -f /usr/local/bin/unison-fsmonitor && brew tap eugenmayer/dockersync && brew install eugenmayer/dockersync/unox
I will reinstall docker-sync for you using the above command (y/N) y
Password:
Your Ruby version is 2.0.0, but your Gemfile specified 2.2.2
Error: Another active Homebrew update process is already in progress.
Please wait for it to finish or terminate it to continue.
Your Ruby version is 2.0.0, but your Gemfile specified 2.2.2
/Users/Me/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.5/lib/bundler/definition.rb:412:in `validate_ruby!': Your Ruby version is 2.0.0, but your Gemfile specified 2.2.2 (Bundler::RubyVersionMismatch)
	from /Users/Me/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.5/lib/bundler.rb:123:in `setup'
	from /Users/Me/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.5/lib/bundler/setup.rb:18:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
     warning  Could not find unison-fsmonitor (unox) binary in $PATH. Trying to install now
```

It appears to be wanting to use the system-level Ruby, not the one currently used by RVM.  I think it's ignoring the `bundle exec` somehow when running this command.

There is no other "active Homebrew update process" going.  I checked, it does this each time.  I ran the `sudo rm -f /usr/local/bin/unison-fsmonitor && brew tap eugenmayer/dockersync && brew install eugenmayer/dockersync/unox` but now the app just doesn't start... it gives the same Ruby version error.

**Comment by EugenMayer** [comment]
I cannot really help you with the RVM issue, we are not using system ruby either, but using rbenv. You might want to uninstall docker-sync, unox and it unison and delete ~/. Docker-sync-global.yml... Then install dockrr-dync using gem install and then just start it. It will try to install unison and unox from the scratch then

**Comment by EugenMayer** [comment]
could it be that you are also using a old, non 0.3.5 docker-sync version?

**Comment by wulftone** [comment]
Unfortunately, this started because I upgraded docker-sync.

**Comment by wulftone** [comment]
Still a problem on docker-sync 0.4.3.  I traced it down to here:
```
From: /Users/me/.rvm/gems/ruby-2.2.2/gems/docker-sync-0.4.3/lib/docker-sync/preconditions/preconditions_osx.rb @ line 106 DockerSync::Preconditions::Osx#unox_available:

    103: def unox_available
    104:   if should_run_precondition?
    105:     `brew list unox`
```

```
/Users/me/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.5/lib/bundler/definition.rb:412:in `validate_ruby!': Your Ruby version is 2.0.0, but your Gemfile specified 2.2.2 (Bundler::RubyVersionMismatch)
	from /Users/me/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.5/lib/bundler.rb:123:in `setup'
	from /Users/me/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.5/lib/bundler/setup.rb:18:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```
It looks like `brew` is trying to do some silly things, not sure what exactly yet is causing it.

**Comment by u007** [comment]
tried this on ruby 2.3 and ruby 2.4, getting this error:
```
/Users/james/.rvm/rubies/ruby-2.3.6/lib/ruby/site_ruby/2.3.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem docker-sync (>= 0.a) with executable docker-sync (Gem::GemNotFoundException)
	from /Users/james/.rvm/rubies/ruby-2.3.6/lib/ruby/site_ruby/2.3.0/rubygems.rb:308:in `activate_bin_path'
	from /Users/james/.rvm/gems/ruby-2.3.6/bin/docker-sync:23:in `<main>'
	from /Users/james/.rvm/gems/ruby-2.3.6/bin/ruby_executable_hooks:15:in `eval'
	from /Users/james/.rvm/gems/ruby-2.3.6/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by u007** [comment]
trying out with docker-sync-stack start, same error, but gem this time is docker-sync-stack

**Comment by EugenMayer** [comment]
sorry not going to debug any rvm issues, anybody using that has to do this on his own.

**Comment by u007** [comment]
ok i think i found the problem. some how due to bundle issue on the mac , it causes the gem missing error. but after rerun bundle install , it works now.
i guess cox ive been mixing bundle install in container linux itself on the same directory
