### ISSUE TITLE
Default host for Docker native

### ISSUE THREAD

**Issue by adiq** [EugenMayer/docker-sync#480]
* Error
* OSX High Sierra `10.13 (17A405)`
* Docker Native `Version 17.10.0-ce-mac36 (19824) Channel: edge a7c7e01149`
* default (native_osx)

docker-sync:
```yml
version: "2"

options:
  verbose: true
  compose-dev-file-path: 'docker-compose.override.yml'
syncs:
  container-sync:
    src: './'
```

When running `start` it fails on:
```
     command  unison -testserver /container_sync "socket://:32768"
/Library/Ruby/Gems/2.3.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/unison.rb:191:in `block in start_container': Failed to start unison container in time, try to increase max_attempt in your configuration. See https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration for more informations (RuntimeError)
	from /Library/Ruby/Gems/2.3.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/unison.rb:187:in `loop'
	from /Library/Ruby/Gems/2.3.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/unison.rb:187:in `start_container'
	from /Library/Ruby/Gems/2.3.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_process.rb:107:in `start_container'
	from /Library/Ruby/Gems/2.3.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:92:in `block in start_container'
	from /Library/Ruby/Gems/2.3.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:91:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:91:in `start_container'
	from /Library/Ruby/Gems/2.3.0/gems/docker-sync-0.4.6/tasks/sync/sync.thor:166:in `daemonize'
	from /Library/Ruby/Gems/2.3.0/gems/docker-sync-0.4.6/tasks/sync/sync.thor:48:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/docker-sync-0.4.6/bin/docker-sync:14:in `<top (required)>'
	from /usr/local/bin/docker-sync:22:in `load'
	from /usr/local/bin/docker-sync:22:in `<main>'
```

This error occurs as there is no host IP address given to unison command. There is some bug either in `Dependencies::Docker::Driver.docker_toolbox?` or `get_host_ip_default` itself. Probably it's the case when you also have docker-machine installed (not running); the quickfix is to define option `sync_host_ip: '127.0.0.1'`.

If someone could look into this it would be great, if not I will handle this later.

_may be connected to https://github.com/EugenMayer/docker-sync/issues/477_

**Comment by EugenMayer** [comment]
please see https://github.com/EugenMayer/docker-sync/pull/478 its related to that - unison is selected instead of native_osx.
