### ISSUE TITLE
docker-sync container cannot be deleted/removed

### ISSUE THREAD

**Issue by jasonellington** [EugenMayer/docker-sync#572]
Hi, I am experiencing errors with my docker-sync. I cannot rm the current container docker-sync is using. I try running ```docker-sync start``` and i receive the error below. If I try removing the container or force remove it, docker hangs and does not remove the container. Not sure where to go from here. I have tried delete my .docker-sync/ directory as well.

### Error
```
docker-sync start
          ok  Starting native_osx for sync docker-sync
docker: Error response from daemon: Conflict. The container name "/docker-sync" is already in use by container "7232ca75c7b285d79d07c96631d2de33c2981ccf7ff6844f539d70771b6162e5". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
/Users/jelling/.rvm/gems/ruby-2.0.0-p648/gems/docker-sync-0.5.7/lib/docker-sync/sync_strategy/native_osx.rb:96:in `start_container': Precopy failed (RuntimeError)
	from /Users/jelling/.rvm/gems/ruby-2.0.0-p648/gems/docker-sync-0.5.7/lib/docker-sync/sync_process.rb:105:in `start_container'
	from /Users/jelling/.rvm/gems/ruby-2.0.0-p648/gems/docker-sync-0.5.7/lib/docker-sync/sync_manager.rb:103:in `block in start_container'
	from /Users/jelling/.rvm/gems/ruby-2.0.0-p648/gems/docker-sync-0.5.7/lib/docker-sync/sync_manager.rb:102:in `each'
	from /Users/jelling/.rvm/gems/ruby-2.0.0-p648/gems/docker-sync-0.5.7/lib/docker-sync/sync_manager.rb:102:in `start_container'
	from /Users/jelling/.rvm/gems/ruby-2.0.0-p648/gems/docker-sync-0.5.7/tasks/sync/sync.thor:163:in `daemonize'
	from /Users/jelling/.rvm/gems/ruby-2.0.0-p648/gems/docker-sync-0.5.7/tasks/sync/sync.thor:47:in `start'
	from /Users/jelling/.rvm/gems/ruby-2.0.0-p648/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/jelling/.rvm/gems/ruby-2.0.0-p648/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/jelling/.rvm/gems/ruby-2.0.0-p648/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/jelling/.rvm/gems/ruby-2.0.0-p648/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Users/jelling/.rvm/gems/ruby-2.0.0-p648/gems/docker-sync-0.5.7/bin/docker-sync:14:in `<top (required)>'
	from /Users/jelling/.rvm/gems/ruby-2.0.0-p648/bin/docker-sync:23:in `load'
	from /Users/jelling/.rvm/gems/ruby-2.0.0-p648/bin/docker-sync:23:in `<main>'
	from /Users/jelling/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jelling/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
```

### docker-sync.yml
```
version: "2"

syncs:
  docker-sync:
    src: './'
    sync_userid: '1000'
    sync_excludes: ['.gitignore', '.git/', '.idea/']
options:
  unison_image: 'eugenmayer/unison:2.51.2.0'
```

### Operating System
High Sierra 10.13.2

**Comment by EugenMayer** [comment]
https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration#docker-syncyml

```
IMPORTANT: Be sure to use a sync-name which is unique, since it will be a container name. Do not use your app name, but rather app-sync
```

**Comment by jasonellington** [comment]
@EugenMayer where exactly do I update the sync-name in my docker-sync.yml or docker-compose.yml?
