### ISSUE TITLE
Can't start docker-sync

### ISSUE THREAD

**Issue by stanleyyylau** [EugenMayer/docker-sync#594]
I can't start docker-sync, it give me below error

### Error/Feature Requestion/Docs
```
Stanleys-MacBook-Pro:docker-wordpress stanley$ docker-sync start
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'docker-sync' (>= 0) among 21 total gem(s) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	from /usr/local/bin/docker-sync:22:in `<main>'
Stanleys-MacBook-Pro:docker-wordpress stanley$ bundle update
```

### Docker Driver
docker for mac

### Sync strategy
I didn't specify a strategy, below is my config file

### your docker-sync.yml

```
version: ‘2’
syncs:
  project_volume_sync:
    src: ‘./app’
    dest: ‘/app’
```

### OS
Mac OS Sierra 10.12.6

**Comment by michalkleiner** [comment]
How did you install docker-sync?
