### ISSUE TITLE
Unox package broken, causing `docker-sync start` failed

### ISSUE THREAD

**Issue by jinjingbo** [EugenMayer/docker-sync#601]
### Error
docker-sync new installation with unox no longer works.

### Error detail
```
$ docker-sync start --foreground
     warning  Could not find eugenmayer/dockersync/unox. Trying to install it now.
Install eugenmayer/dockersync/unox for you? [y/N] y
     command  brew install eugenmayer/dockersync/unox

==> Installing unox from eugenmayer/dockersync
==> Downloading https://codeload.github.com/hnsl/unox/tar.gz/0.2.0
Already downloaded: /Users/profileName/Library/Caches/Homebrew/unox--0.2.0.gz
Error: Failure while executing; `gunzip -q -N -- /private/tmp/d20180827-2871-14kki0a/0.2.0` exited with 1.
       error  Failed to install required package. Please install it manually and try again.

```

### Related to this issue
https://github.com/EugenMayer/homebrew-dockersync/issues/6

### Sync strategy
unison

### OS
OSX 10.13.6

**Comment by simonfranzen** [comment]
I have the same problem

```
Homebrew 1.7.2
Homebrew/homebrew-core (git revision 6ff8b; last commit 2018-08-29)
MacBook-Pro-3:~ simon$ brew install eugenmayer/dockersync/unox -debug -verbose
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/eugenmayer/homebrew-dockersync/Formula/unox.rb
==> Installing unox from eugenmayer/dockersync
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::AliasLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/usr/bin/sandbox-exec -f /private/tmp/homebrew20180829-54300-10r6j00.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0:/usr/local/Homebrew/Library/Homebrew/cask/lib:/usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/eugenmayer/homebrew-dockersync/Formula/unox.rb --git --verbose --debug
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/eugenmayer/homebrew-dockersync/Formula/unox.rb
==> Downloading https://codeload.github.com/hnsl/unox/tar.gz/0.2.0
Already downloaded: /Users/simon/Library/Caches/Homebrew/unox--0.2.0.gz
==> Verifying unox--0.2.0.gz checksum
gunzip -N -- /private/tmp/d20180829-54302-16sme28/0.2.0
gunzip: /private/tmp/d20180829-54302-16sme28/0.2.0: unknown suffix -- ignored
Error: Failure while executing; `gunzip -N -- /private/tmp/d20180829-54302-16sme28/0.2.0` exited with 1. Here's the output:
gunzip: /private/tmp/d20180829-54302-16sme28/0.2.0: unknown suffix -- ignored

/usr/local/Homebrew/Library/Homebrew/system_command.rb:101:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:46:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:23:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:16:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/gzip.rb:20:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:119:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:126:in `block in extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:123:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:54:in `stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:97:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:170:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
/usr/local/Homebrew/Library/Homebrew/resource.rb:169:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:96:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:74:in `stage'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/forwardable.rb:202:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2018:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1116:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:113:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:559:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:110:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:191:in `<main>'

```

**Comment by jinjingbo** [comment]
This possibly  fixed it:  
https://github.com/d4rky-pl/homebrew-dockersync/commit/cfa29f1bba1a29ad557dedcad88c801b04bf690d

**Comment by jinjingbo** [comment]
PR created: https://github.com/EugenMayer/homebrew-dockersync/pull/7

**Comment by EugenMayer** [comment]
fixed, thanks for the work!
