### ISSUE TITLE
Wercker throws volume segmentation violation trying to use docker-sync'ed volume

### ISSUE THREAD

**Issue by skinderis** [EugenMayer/docker-sync#658]
!!!! Important hint !!!!!

> Please do not create issues for [docker](https://docs.docker.com/) or [docker-compose](https://docs.docker.com/compose/reference) related questions. Ensure you understand the tools properly and consult their documentation first. Please understand what [docker volumes](https://docs.docker.com/engine/admin/volumes/volumes/) / [docker-compose volumes](https://docs.docker.com/compose/compose-file/compose-file-v2/#specifying-byte-values)

> Please be sure to have a look at our [documentation](https://github.com/EugenMayer/docker-sync/wiki) too, especially [configuration](https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration) and our starting point the [boilerplate](https://github.com/EugenMayer/docker-sync-boilerplate)

### Error

I am running my project using wercker, but it is not can't be run because of some segmentation violation

```
--> No Docker host specified, checking: /var/run/docker.sock
--> Executing pipeline: dev
--> Copied working directory: 0.00s
--> Running step: setup environment
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19bd0f2]

goroutine 1 [running]:
github.com/wercker/wercker/docker.NewDockerPipeline(0x1d1c09e, 0x3, 0xc420292f50, 0xc4201ea480, 0xc4201916b0, 0x1e0a300, 0xc42041a9c0, 0x10, 0xc42018d5f0, 0xc42018d638)
	/go/src/github.com/wercker/wercker/docker/pipeline.go:80 +0x1b2
github.com/wercker/wercker/docker.NewDockerBuild(0x1d1c09e, 0x3, 0xc420292f50, 0xc4201ea480, 0xc4201916b0, 0x1e0a300, 0xc42041a9c0, 0xc420473b20, 0x5, 0xc420473b30)
	/go/src/github.com/wercker/wercker/docker/build.go:31 +0x77
github.com/wercker/wercker/cmd.GetDevPipelineFactory.func1(0xc420292f50, 0xc4201ea480, 0xc4201916b0, 0x10, 0xc42018d638, 0xc42018d5f0, 0xc420508cf0)
	/go/src/github.com/wercker/wercker/cmd/runner.go:51 +0x11b
github.com/wercker/wercker/cmd.(*Runner).GetPipeline(0xc420422a00, 0xc420292f50, 0xc4201916b0, 0x0, 0x0, 0x1)
	/go/src/github.com/wercker/wercker/cmd/runner.go:429 +0x45
github.com/wercker/wercker/cmd.(*Runner).SetupEnvironment(0xc420422a00, 0x28b2098, 0xc420348900, 0x0, 0x0, 0x0)
	/go/src/github.com/wercker/wercker/cmd/runner.go:634 +0x657
github.com/wercker/wercker/cmd.executePipeline(0x28b2098, 0xc420348900, 0xc4201ea480, 0xc4201916b0, 0xc4201fd6c0, 0x0, 0x0, 0x0)
	/go/src/github.com/wercker/wercker/cmd/main.go:1147 +0x762
github.com/wercker/wercker/cmd.cmdDev(0x28b2060, 0xc4200380e0, 0xc4201ea480, 0xc4201916b0, 0xc420348090, 0xc4201916b0, 0x0)
	/go/src/github.com/wercker/wercker/cmd/main.go:601 +0xc2
github.com/wercker/wercker/cmd.glob..func2(0xc420200000)
	/go/src/github.com/wercker/wercker/cmd/main.go:99 +0x404
github.com/wercker/wercker/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x1b0b040, 0x1d70b40, 0xc420200000, 0xc4201f0000, 0x0)
	/go/src/github.com/wercker/wercker/vendor/gopkg.in/urfave/cli.v1/app.go:492 +0x7c
github.com/wercker/wercker/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0x1d1c09e, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1d3d7b3, 0x1f, 0x0, ...)
	/go/src/github.com/wercker/wercker/vendor/gopkg.in/urfave/cli.v1/command.go:210 +0xa36
github.com/wercker/wercker/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc42021e680, 0xc42002e0c0, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/wercker/wercker/vendor/gopkg.in/urfave/cli.v1/app.go:255 +0x6a0
main.main()
	/go/src/github.com/wercker/wercker/main.go:25 +0x4b
```

### Docker Driver
d4m 

### Sync strategy
native_osx

### your docker-sync.yml

version: "2"

```
options:
  verbose: true
  compose-dev-file-path: 'docker-compose-dev.yml'
syncs:
  my-volume-sync:
    src: '.'
    sync_strategy: 'native_osx'
    watch_args: '-v'

```
### OS
OSX

**Comment by EugenMayer** [comment]
Going to close this issue for now, unknown, not ever reported sehfault on one system - that sounds like a local issue, sorry
