### ISSUE TITLE
missing operand error when starting on WSL using unison

### ISSUE THREAD

**Issue by Martaver** [EugenMayer/docker-sync#665]
### Error
When trying to start`docker-sync` with `unison` sync strategy, the start fails with repeated "missing operand" errors. Log below:

```
       note:  You can also run docker-sync in the background with docker-sync start
          ok  Starting unison for sync smoothteam
dirname: missing operand
Try 'dirname --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
doing initial sync with unison
Unison 2.51.2 (ocaml 4.06.1): Contacting server...
Looking for changes
Reconciling changes
Propagating updates
UNISON 2.51.2 (OCAML 4.06.1) started propagating changes at 20:02:40.47 on 28 Jun 2019
[BGN] Copying  from /app_sync to /host_sync
[END] Copying
UNISON 2.51.2 (OCAML 4.06.1) finished propagating changes at 20:02:40.47 on 28 Jun 2019
Saving synchronizer state
Synchronization complete at 20:02:40  (1 item transferred, 0 skipped, 0 failed)
real    0m 0.11s
user    0m 0.06s
sys     0m 0.00s
chown ing file to uid 0
dirname: missing operand
Try 'dirname --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
Traceback (most recent call last):
        15: from /usr/local/bin/docker-sync-stack:23:in `<main>'
        14: from /usr/local/bin/docker-sync-stack:23:in `load'
        13: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/bin/docker-sync-stack:15:in `<top (required)>'
        12: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        11: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        10: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         9: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         8: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/tasks/stack/stack.thor:46:in `start'
         7: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_manager.rb:110:in `run'
         6: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_manager.rb:110:in `each'
         5: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_manager.rb:111:in `block in run'
         4: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_process.rb:85:in `run'
         3: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_strategy/unison.rb:39:in `run'
         2: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_strategy/unison.rb:211:in `start_container'
         1: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_strategy/unison.rb:211:in `loop'
/var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_strategy/unison.rb:216:in `block in start_container': Failed to start unison container in time, try to increase max_attempt (currently 10) in your configuration. See https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration for more informations (RuntimeError)
error Command failed with exit code 1.
```

This is on a fresh install of Ubuntu, with same results as before the reinstall.

### Docker Driver
Docker for Windows exposing docker daemon to docker CLI in Windows Subsystem for Linux

### Sync strategy
unison

### OS
ubuntu 18.04.2 LTS bionic as Windows Subsystem for Linux

Any ideas?

**Comment by EugenMayer** [comment]
Stalled, closing
