### ISSUE TITLE
Running `docker-sync start` result in "error while mounting volume: no such file or directory"

### ISSUE THREAD

**Issue by msor-ciklum** [EugenMayer/docker-sync#677]
### Error/Feature Requestion/Docs
Error

### Docker Driver
Microsoft Hyper-V

### Sync strategy
native_osx

### your docker-sync.yml
```
version: "2"

options:
  verbose: true
syncs:
  lommelegen-admin-sync:
    sync_strategy: 'native_osx'
    src: './lommelegen-admin/'
  lommelegen-api-sync:
    sync_strategy: 'native_osx'
    src: './lommelegen-api/'
  lommelegen-front-sync:
    sync_strategy: 'native_osx'
    src: './lommelegen-front/'
```

### OS
Windows 10 Pro (10.0.17763 Build 17763)

### Problem
Running `docker-sync start` result in "error while mounting volume: no such file or directory"
Full log:
```
ziqul@DESKTOP-KPSDDAU:/c/Users/Maxim/Projects/lommelegen-meta$ docker-sync start -f
/var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/update_check.rb:41: warning: Insecure world writable dir /c in PATH, mode 040777
       note:  Starting in foreground mode
          ok  Starting native_osx for sync lommelegen-admin-sync
          ok  lommelegen-admin-sync container not running
          ok  creating lommelegen-admin-sync container
          ok  Starting precopy
     precopy  docker run --rm -v "lommelegen-admin-sync:/app_sync" -v "/c/Users/Maxim/Projects/lommelegen-meta/lommelegen-admin:/host_sync" -e HOST_VOLUME=/host_sync -e APP_VOLUME=/app_sync -e TZ=$(basename $(dirname `readlink /etc/localtime`))/$(basename `readlink /etc/localtime`) -e UNISON_SRC="/host_sync" -e UNISON_DEST="/app_sync" -e UNISON_ARGS="  -prefer /host_sync -numericids -auto -batch" -e UNISON_WATCH_ARGS="-repeat watch"  --name lommelegen-admin-sync eugenmayer/unison:2.51.2.1 /usr/local/bin/precopy_appsync
docker: Error response from daemon: error while mounting volume '/var/lib/docker/volumes/lommelegen-admin-sync/_data': failed to mount local volume: mount /mnt/c/Users/Maxim/Projects/lommelegen-meta/lommelegen-admin/:/var/lib/docker/volumes/lommelegen-admin-sync/_data, flags: 0x1000: no such file or directory.
Traceback (most recent call last):
        15: from /usr/local/bin/docker-sync:23:in `<main>'
        14: from /usr/local/bin/docker-sync:23:in `load'
        13: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/bin/docker-sync:14:in `<top (required)>'
        12: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        11: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        10: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         9: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         8: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/tasks/sync/sync.thor:50:in `start'
         7: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/tasks/sync/sync.thor:50:in `chdir'
         6: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/tasks/sync/sync.thor:51:in `block in start'
         5: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_manager.rb:110:in `run'
         4: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_manager.rb:110:in `each'
         3: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_manager.rb:111:in `block in run'
         2: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_process.rb:85:in `run'
         1: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_strategy/native_osx.rb:116:in `run'
/var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_strategy/native_osx.rb:96:in `start_container': Precopy failed (RuntimeError)
```

I believe it has something to do with docker-sync trying to mount volume from "/mnt/c/..." instead of "/c/...", but these should not be the deal since I am running command from "/c/Users/Maxim/Projects/lommelegen-meta" (notice path starting from "c").

**Comment by EugenMayer** [comment]
As far as I know we are only compatible with docker for windows, not the hyperv variant - not sure though

**Comment by msor-ciklum** [comment]
As far as I know running Docker for Windows now require Hyper-V (https://runnable.com/docker/install-docker-on-windows-10).

Please let me know if I have any options, or just should dump idea running `docker-sync` using my setup.

**Comment by EugenMayer** [comment]
@msor-ciklum sorry, as stated on other tickets - i am not supporting the windows setup myself. It was considered beta and the people wanted to maintain it, left ( or changed os and lost interest ). 

I cannot really help you a lot here, neither i have a setup to test nor do i plan to have one. 

Did you look at https://docker-sync.readthedocs.io/en/latest/getting-started/installation.html#windows
Also check the issues labeled with windows.

At least, to my last knowledge, ds was running and usefull under windows. Sorry to be not of any more help

**Comment by msor-ciklum** [comment]
@EugenMayer, no worries, you are actually being a great help.
Thanks for reply.

**Comment by EugenMayer** [comment]
Closing this issue due to innactivity - hope you solved your issue in the meantime
