### ISSUE TITLE
Ubuntu18.04 fails on running 'simplest' demo from boilerplate

### ISSUE THREAD

**Issue by bauerjj** [EugenMayer/docker-sync#686]
### Docker Driver
Native Linux

### Sync strategy
default

### your docker-sync.yml
I'm using the virgin files from docker-sync-boilerplate

### OS
Linux

### Problem

```
git clone https://github.com/EugenMayer/docker-sync-boilerplate.git
cd docker-sync-boilerplate/simplest
sudo docker-sync-stack start
```
yields:
```
note:  You can also run docker-sync in the background with docker-sync start
     success  Docker volume for simplest-sync created
          ok  Found implicit docker-compose-dev.yml and using it from /home/xxx/Documents/docker-sync-boilerplate/simplest/docker-compose-dev.yml
          ok  starting compose
#<Thread:0x0000557fff269330@/var/lib/gems/2.5.0/gems/docker-sync-0.5.11/tasks/stack/stack.thor:50 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	6: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/tasks/stack/stack.thor:51:in `block in start'
	5: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/compose.rb:42:in `run'
	4: from /var/lib/gems/2.5.0/gems/docker-compose-1.1.12/lib/docker/compose/session.rb:98:in `up'
	3: from /var/lib/gems/2.5.0/gems/docker-compose-1.1.12/lib/docker/compose/session.rb:266:in `run!'
	2: from /var/lib/gems/2.5.0/gems/backticks-1.0.2/lib/backticks/runner.rb:103:in `run'
	1: from /var/lib/gems/2.5.0/gems/backticks-1.0.2/lib/backticks/runner.rb:134:in `run_without_sugar'
/var/lib/gems/2.5.0/gems/backticks-1.0.2/lib/backticks/runner.rb:134:in `spawn': No such file or directory - docker-compose (Errno::ENOENT)
EXCEPTION: #<Errno::ENOENT: No such file or directory - docker-compose>
MESSAGE: No such file or directory - docker-compose
```

`Docker version 19.03.3, build a872fc2f86`
`Docker-sync version == 0.5.11`

**Comment by ignatiusreza** [comment]
Looks like `docker-compose` is not installed in your machine, please ensure that it is by runnning `which docker-compose`:

```
$ which docker-compose
/usr/local/bin/docker-compose
```

Please follow the official instruction on installing `docker-compose` to proceed: https://docs.docker.com/compose/install/
