### ISSUE TITLE
Upgrading to v(0.5.13) breaks in sync.thor

### ISSUE THREAD

**Issue by the-graytest** [EugenMayer/docker-sync#694]
### Error/Feature Requestion/Docs
After upgrading from v(0.5.11) to v(0.5.13) docker/sync breaks  upon running due to an error in 'sync.thor' this issue has been replicated by at least 3 others in our org. 

Stack Trace: 
```
docker-sync installed. Continuing...
[user_path]/.rvm/gems/ruby-2.4.4[@repo-name]/gems/docker-sync-0.5.13/tasks/sync/sync.thor:159:in `daemonize': undefined method `empty?' for nil:NilClass (NoMethodError)
        from [user_path]/.rvm/gems/ruby-2.4.4[@repo-name]/gems/docker-sync-0.5.13/tasks/sync/sync.thor:47:in `start'
        from [user_path]/.rvm/gems/ruby-2.4.4[@repo-name]/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from [user_path]/.rvm/gems/ruby-2.4.4[@repo-name]/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from [user_path]/.rvm/gems/ruby-2.4.4[@repo-name]/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from [user_path]/.rvm/gems/ruby-2.4.4[@repo-name]/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from [user_path]/.rvm/gems/ruby-2.4.4[@repo-name]/gems/docker-sync-0.5.13/bin/docker-sync:14:in `<top (required)>'
        from [user_path]/.rvm/gems/ruby-2.4.4[@repo-name]/bin/docker-sync:23:in `load'
        from [user_path]/.rvm/gems/ruby-2.4.4[@repo-name]/bin/docker-sync:23:in `<main>'
        from [user_path]/.rvm/gems/ruby-2.4.4[@repo-name]/bin/ruby_executable_hooks:24:in `eval'
        from [user_path]/.rvm/gems/ruby-2.4.4[@repo-name]/bin/ruby_executable_hooks:24:in `<main>'
```

### Docker Driver
docker for mac

### Sync strategy
? (default/native_osx/unison/rsync)

### your docker-sync.yml

```yaml
version: 2
syncs:
  app-sync:
    src: './'
    sync_excludes: ['.docker-sync', '.git', 'log', 'tmp/cache']
```

### OS
OSX Catalina

**Comment by EugenMayer** [comment]
Please paste your `docker-sync.yml`

**Comment by the-graytest** [comment]
`version: 2
syncs:
  app-sync:
    src: './'
    sync_excludes: ['.docker-sync', '.git', 'log', 'tmp/cache']
`

**Comment by EugenMayer** [comment]
This means that the defined sync-name has not been found

https://github.com/EugenMayer/docker-sync/blob/master/tasks/sync/sync.thor#L159

and thus it is null.

I guess you simply upgrade during running the dameon mode, which is not supported. please uninstall and install docker-sync using gem

```
gem uninstall docker-sync
gem install docker-sync
```

This should fix it

**Comment by the-graytest** [comment]
that resolved it, thanks 👍 

I'll go ahead and close this :)

**Comment by EugenMayer** [comment]
Thank you :)
