### ISSUE TITLE
docker/volumes/appcode-native-osx-sync/_data, flags: 0x1000: no such file or directory

### ISSUE THREAD

**Issue by asolopovas** [EugenMayer/docker-sync#702]
Hi, 
I am trying to setup docker sync in Windows. I have gone through `https://docker-sync.readthedocs.io/en/latest/getting-started/installation.html` but was not successful in making it work. Then I decided to subscribe for windows insider slow ring with wsl2 to see if thing were different be in both attempts I cam to the same problem that looks like this. 

```
andrius@Andrius-Dell:~/dev/docker-sync-boilerplate/default$ docker-sync-stack start
/var/lib/gems/2.5.0/gems/docker-sync-0.5.14/lib/docker-sync/update_check.rb:41: warning: Insecure world writable dir /mnt/c/Python38/Scripts/ in PATH, mode 040777
       note:  You can also run docker-sync in the background with docker-sync start
     command  docker volume create --opt type=none --opt device="/home/andrius/dev/docker-sync-boilerplate/default/app" --opt o=bind --name appcode-native-osx-sync
     success  Docker volume for appcode-native-osx-sync created
     success  Watcher disabled by configuration
          ok  Found implicit docker-compose-dev.yml and using it from /home/andrius/dev/docker-sync-boilerplate/default/docker-compose-dev.yml
          ok  starting compose
Creating network "default_default" with the default driver
Pulling app-native-osx (alpine:)...
latest: Pulling from library/alpine
89d9c30c1d48: Pull complete
Digest: sha256:c19173c5ada610a5989151111163d28a67368362762534d8a8121ce95cf2bd5a
Status: Downloaded newer image for alpine:latest
Creating default_app-native-osx_1 ... 
[23064] Failed to execute script docker-compose

ERROR: for default_app-native-osx_1  a bytes-like object is required, not 'str'

ERROR: for app-native-osx  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/119150d6ea49e09c30b03fd672ef7c006e726e7f99ef208dfe61de47f77b43f8/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compose/service.py", line 625, in start_container
  File "compose/container.py", line 241, in start
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 1095, in start
  File "site-packages/docker/api/client.py", line 263, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b"error while mounting volume '/var/lib/docker/volumes/appcode-native-osx-sync/_data': failed to mount local volume: mount /home/andrius/dev/docker-sync-boilerplate/default/app:/var/lib/docker/volumes/appcode-native-osx-sync/_data, flags: 0x1000: no such file or directory"")   

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1106, in up
  File "compose/cli/main.py", line 1102, in up
  File "compose/project.py", line 570, in up
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/project.py", line 556, in do
  File "compose/service.py", line 546, in execute_convergence_plan
  File "compose/service.py", line 467, in _execute_convergence_create
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/service.py", line 465, in <lambda>
  File "compose/service.py", line 457, in create_and_start
  File "compose/service.py", line 627, in start_container
TypeError: a bytes-like object is required, not 'str'
#<Thread:0x000055f67a994ac8@/var/lib/gems/2.5.0/gems/docker-sync-0.5.14/tasks/stack/stack.thor:50 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        3: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.14/tasks/stack/stack.thor:51:in `block in start'
        2: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.14/lib/docker-sync/compose.rb:42:in `run'
        1: from /var/lib/gems/2.5.0/gems/docker-compose-1.1.12/lib/docker/compose/session.rb:98:in `up'
                                                                                                                                           (Docker::Compose::Error)
                                                                                   >
```

I kinda see that it can't find a volumes directory but am not sure what to do to get it to work. Please help spent 20 hours fiddling with it but can't get it to work. Thanks in advance.

### your docker-sync.yml
https://github.com/EugenMayer/docker-sync-boilerplate/tree/master/default

### OS
? (OSX Version/Linux)
Windows 10 Pro Build 19037.1

**Comment by EugenMayer** [comment]
You should not use the default boilerplate since it uses the wrong strategy.

For windows AFAIK unison is the only choice right now, so https://github.com/EugenMayer/docker-sync-boilerplate/tree/master/unison

see step https://docker-sync.readthedocs.io/en/latest/getting-started/installation.html#let-s-go step 9 for installing OCALM / unison.

Hope this helps

**Comment by EugenMayer** [comment]
Stalled,  closing
