### ISSUE TITLE
native_osx strategy does not run when running docker-sync from subfolder

### ISSUE THREAD

**Issue by ostrolucky** [EugenMayer/docker-sync#729]
### Error/Feature Requestion/Docs
```
➜ ls ../docker-sync.yml
../docker-sync.yml
➜ docker-sync start
          ok  Starting native_osx for sync community-sync
Traceback (most recent call last):
	14: from /Users/gostrolucky/.gem/ruby/2.6.0/bin//docker-sync:23:in `<main>'
	13: from /Users/gostrolucky/.gem/ruby/2.6.0/bin//docker-sync:23:in `load'
	12: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/docker-sync-0.5.14/bin/docker-sync:14:in `<top (required)>'
	11: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	10: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 9: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 8: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 7: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/docker-sync-0.5.14/tasks/sync/sync.thor:47:in `start'
	 6: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/docker-sync-0.5.14/tasks/sync/sync.thor:170:in `daemonize'
	 5: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/docker-sync-0.5.14/lib/docker-sync/sync_manager.rb:102:in `start_container'
	 4: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/docker-sync-0.5.14/lib/docker-sync/sync_manager.rb:102:in `each'
	 3: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/docker-sync-0.5.14/lib/docker-sync/sync_manager.rb:103:in `block in start_container'
	 2: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/docker-sync-0.5.14/lib/docker-sync/sync_process.rb:105:in `start_container'
	 1: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/docker-sync-0.5.14/lib/docker-sync/sync_strategy/native_osx.rb:41:in `start_container'
/Users/gostrolucky/.gem/ruby/2.6.0/gems/docker-sync-0.5.14/lib/docker-sync/sync_strategy/native_osx.rb:41:in `realpath': No such file or directory @ realpath_rec - /Users/gostrolucky/PhpstormProjects/calida/community/community (Errno::ENOENT)
➜ cd ..
➜ docker-sync start
          ok  Starting native_osx for sync community-sync
          ok  community-sync container still running, restarting unison in container
unison: stopped
unison: started
     success  Sync container started
          ok  Starting native_osx for sync shop-sync
shop-sync
unix:///tmp/supervisor.sock no such file
     success  Sync container started
     success  Starting Docker-Sync in the background
```

### Docker Driver
d4m

### Sync strategy
default

### your docker-sync.yml
irrelevant

### OS
MacOS Catalina

**Comment by EugenMayer** [comment]
Not sure were docker-sync does allow that to be done in general, does it? Seems like we internally expect that your pwd is the folder of docker-sync.yml -most probably to work with all the mounts and such.

Nevertheless, there is surely a way to get it running, but i rarely seen anybody using this nor reporting an issue with that - so not going to work on this support in particular. Feel free to PR if you like, i would merge it if it is not complicating things overall

**Comment by ostrolucky** [comment]
Hello, thanks for response. I actually got an idea that docker-sync should have this behaviour from reading the source code at https://github.com/EugenMayer/docker-sync/blob/a9516f0c7413cf48673526a3832c4e054c97ccb5/lib/docker-sync/config/config_locator.rb#L36 
It makes sense TBH, as docker-compose works perfectly from subfolders as well

**Comment by ostrolucky** [comment]
There is an option for this, see #741
