### ISSUE TITLE
The "- C" parameter causes an error

### ISSUE THREAD

**Issue by feilisu** [EugenMayer/docker-sync#796]
### Error
2022/03/17 11:21:25 /usr/local/bin/docker-sync start -c /usr/local/var/feilisu/open-source/easydock/Kernel/easydock/docker-sync.yml
          ok  Starting unison for sync project
doing initial sync with unison
Unison 2.51.3 (ocaml 4.12.0): Contacting server...
Looking for changes
Reconciling changes
Propagating updates
UNISON 2.51.3 (OCAML 4.12.0) started propagating changes at 11:21:37.00 on 17 Mar 2022
[BGN] Copying  from /app_sync to /host_sync
[END] Copying 
UNISON 2.51.3 (OCAML 4.12.0) finished propagating changes at 11:21:37.00 on 17 Mar 2022
Saving synchronizer state
Synchronization complete at 11:21:37  (1 item transferred, 0 skipped, 0 failed)
real    0m 0.48s
user    0m 0.24s
sys     0m 0.13s
chown ing file to uid 0
initial sync done using unison
/Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/sync_strategy/unison.rb:226:in `block in start_container': Failed to start unison container in time, try to increase max_attempt (currently 10) in your configuration. See https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration for more informations (RuntimeError)
        from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/sync_strategy/unison.rb:219:in `loop'
        from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/sync_strategy/unison.rb:219:in `start_container'
        from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/sync_process.rb:105:in `start_container'
        from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/sync_manager.rb:103:in `block in start_container'
        from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/sync_manager.rb:102:in `each'
        from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/sync_manager.rb:102:in `start_container'
        from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/tasks/sync/sync.thor:181:in `daemonize'
        from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/tasks/sync/sync.thor:47:in `start'
        from /Library/Ruby/Gems/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /Library/Ruby/Gems/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        from /Library/Ruby/Gems/2.6.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/bin/docker-sync:14:in `<top (required)>'
        from /usr/local/bin/docker-sync:23:in `load'
        from /usr/local/bin/docker-sync:23:in `<main>'
2022/03/17 11:21:51 执行失败:
Unison 2.51.3 (ocaml 4.12.0): Contacting server...
Looking for changes
Reconciling changes
Propagating updates
UNISON 2.51.3 (OCAML 4.12.0) started propagating changes at 11:21:37.00 on 17 Mar 2022
[BGN] Copying  from /app_sync to /host_sync
[END] Copying 
UNISON 2.51.3 (OCAML 4.12.0) finished propagating changes at 11:21:37.00 on 17 Mar 2022
Saving synchronizer state
Synchronization complete at 11:21:37  (1 item transferred, 0 skipped, 0 failed)
real    0m 0.48s
user    0m 0.24s
sys     0m 0.13s
/Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/sync_strategy/unison.rb:226:in `block in start_container': Failed to start unison container in time, try to increase max_attempt (currently 10) in your configuration. See https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration for more informations (RuntimeError)
        from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/sync_strategy/unison.rb:219:in `loop'
        from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/sync_strategy/unison.rb:219:in `start_container'
        from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/sync_process.rb:105:in `start_container'
        from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/sync_manager.rb:103:in `block in start_container'
        from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/sync_manager.rb:102:in `each'
        from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/lib/docker-sync/sync_manager.rb:102:in `start_container'
        from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/tasks/sync/sync.thor:181:in `daemonize'
        from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/tasks/sync/sync.thor:47:in `start'
        from /Library/Ruby/Gems/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /Library/Ruby/Gems/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        from /Library/Ruby/Gems/2.6.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.7.1/bin/docker-sync:14:in `<top (required)>'
        from /usr/local/bin/docker-sync:23:in `load'
        from /usr/local/bin/docker-sync:23:in `<main>'

### Docker Driver
docker-machine

### Sync strategy
unison

### docker-sync.yml
`version: '2'
syncs:
  project:
    src: './../../Workspace/Project'
    sync_strategy: 'unison'
    notify_terminal: true
    max_attempt: 10
    sync_excludes_type: 'Name'
    sync_excludes: []`

### OS
OSX

**Comment by feilisu** [comment]
Do not use "- C" parameter, in docker sync YML peer directory startup is normal

**Comment by feilisu** [comment]
Do not use "- C" parameter, in docker sync YML peer directory startup is normal

**Comment by feilisu** [comment]
Resolved, I'm at docker sync The root directory is specified in yaml
