### ISSUE TITLE
Docker sync daemon is crashing

### ISSUE THREAD

**Issue by alexbyk** [EugenMayer/docker-sync#812]
### Error/Feature Requestion/Docs
````
Traceback (most recent call last):
  File "/usr/local/bin/unison-fsmonitor", line 24, in <module>
    from watchdog.observers import Observer
  File "/usr/local/Cellar/unox/0.2.0_1/libexec/lib/python3.10/site-packages/watchdog/observers/__init__.py", line 76, in <module>
    from .polling import PollingObserver as Observer
  File "/usr/local/Cellar/unox/0.2.0_1/libexec/lib/python3.10/site-packages/watchdog/observers/polling.py", line 43, in <module>
    from watchdog.observers.api import (
  File "/usr/local/Cellar/unox/0.2.0_1/libexec/lib/python3.10/site-packages/watchdog/observers/api.py", line 23, in <module>
    from watchdog.utils.bricks import SkipRepeatsQueue
  File "/usr/local/Cellar/unox/0.2.0_1/libexec/lib/python3.10/site-packages/watchdog/utils/bricks.py", line 175, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'
Fatal error: File monitoring helper program not running
```

### Docker Driver
docker-machine+vbox/fusion

### Sync strategy
default

### your docker-sync.yml
xxx
### OS
latest

**Comment by EugenMayer** [comment]
Sorry, but you really have to put minimal effort into using a open-source project. This is not a payed support issue queue with any kind of service promise.

We are all opting in time to help others - but you have to put your fair share into that.

This is a known unox issue, googling for that will help.

**Comment by alexbyk** [comment]
so, I can say all new installations are broken after python 9.10

**Comment by EugenMayer** [comment]
See more on https://github.com/EugenMayer/homebrew-dockersync/tree/master/Formula and https://github.com/EugenMayer/homebrew-dockersync/issues/17

**Comment by wfnuser** [comment]
Thanks.
